### ISSUE TITLE
Add support for glibc 2.28

### ISSUE THREAD

**Issue by dweth** [LaussenLabs/atriumdb#4]
I am trying to install the Python SDK for AtriumDB, and used 'pip install atriumdb' for installation.  It is successful, and I can successfully import it in Python, but when I try to invoke it with """sdk = AtriumSDK(dataset_location='./first.db')""" I get the following error message:

OSError: /path/to/.local/lib/python3.11/site-packages/bin/libTSC.so: cannot open shared object file: No such file or directory

I cannot find anything called libTSC.so in my path, and when I try to install from source libTSC.so doesn't get created.  Any guidance on how to handle this would be appreciated.

I am on Linux Red Hat Enterprise using Python 3.11.5.

**Comment by bgreer101** [comment]
Hi @dweth,

We have seen this before on Windows with Defender deleting the DLL, but being on RHEL, this is new. Do you have any environment scanner / security software running?

I have tried to reproduce your error with:

`conda create -n "atriumdb-test-py311" python=3.11.5`
`conda activate atriumdb-test-py311`
`pip install atriumdb`
`python test.py`

where test.py contains:

```python
from atriumdb import AtriumSDK
sdk = AtriumSDK.create_dataset(dataset_location="./new_dataset2")
``` 

but have been unable to.

A few things to try:

1. Try creating a clean environment using conda or the like and pip installing on that (like what I did in my reproduction)
2. If the above doesn't work, try downloading the whl file from our latest and install it manually:
[https://github.com/LaussenLabs/atriumdb/releases/tag/2.2.2](url) 

and install with `pip install wheel` followed by `pip install atriumdb-2.2.2-py3-none-any.whl`

If this still doesn't work, reach back out. We want to get you up and running and if there are any bugs here, we want to get them patched for you / others in the future.

Also a tip: The "dataset_location" parameter should be a directory and not a file. AtriumDB will build the dataset directory structure, including the metadata database within that directory.

Cheers.

**Comment by dweth** [comment]
Thanks for your help.  I followed the instructions and received the same error.

I did however find that pip was bypassing installing some packages because they were already located in usr/.local/lib/python3.11/site-packages, and not being created in my conda environment.  I deleted these packages and tried again, and got a different error message when I attempt to invoke the SDK from Python.  It seems libTSC.so is now built, but it needs GLIBC_2.29.  Our Red Hat distribution uses version 2.28.  Is this adequate if we build from source?

Error:
OSError: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /path/to/user/.conda/envs/atriumdb-test-py311/lib/python3.11/site-packages/bin/libTSC.so)

**Comment by bgreer101** [comment]
We have tried doing exactly that - building with glibc at 2.28 on an older build but ran into some compatibility issues in our build code that would require substantial work to address. Is it possible for you to upgrade this machine to >= 2.29 (not sure if RHEL supports this)? 2.28 came out over 5 years ago now and RHEL 8 (which i assume you're on) is on the verge of going out of full support so I am a bit reluctant to create this backwards compatibility.

If upgrading isn't an option, I think your best bet would be to create a Python 3.10+ Docker container that contains the required libraries (Ubuntu 20 base image would have these) and has AtriumDB installed in it. That should allow you to get up and running independent of system versions. If you're unfamiliar with how to do this, i am happy to post some instructions on how to set it up.

**Comment by dweth** [comment]
We don't have Docker on our HPC system, but we do have Singularity.  I'm having trouble getting this up and running; all of my attempts that have resulted in successful import of the SDK in python then result in the same GLIBC version error.  For example, these steps produce that error:

Singularity definition file in tsc-lib/ (AtriumDB.def):
___________
Bootstrap: docker
From: ubuntu:20.04

%post
    export DEBIAN_FRONTEND=noninteractive
    apt-get update && apt-get install -y tzdata cmake build-essential gdb libzstd-dev liblz4-dev python3.10 mingw-w64
    rm -rf /var/lib/apt/lists/*

    sed -i -e 's/\r$//' /build_release.sh
    sed -i -e 's/\r$//' /build_debug.sh

    chmod 755 /build_release.sh
    chmod 755 /build_debug.sh

%files
    build_release.sh /
    build_debug.sh /

%environment
    export TZ="America/Toronto"

%runscript
    /bin/bash
______________

singularity build atriumdb.sif AtriumDB.def
singularity exec --bind /path/to/folder:/atriumdb atriumdb.sif ./build_release.sh 
cd ../sdk
pip install build
python -m build
cd ./dist/
pip install atriumdb-2.2.2-py3-none-any.whl

These instructions succeed, but then I get the GLIBC error when I open python, import the SDK, and try to invoke it.

**Comment by bgreer101** [comment]
Hi @dweth,

Just want to keep you posted. We are scoping internally around supporting GLIBC 2.28. The are enough modern/semi distro's around that still use it that I think it's worthwhile supporting. Let me know if you've had any more success.

**Comment by dweth** [comment]
Thanks for your help!  As of a couple hours ago we actually determined a solution that works (for now).  This Singularity definition file and these steps allow me to import and invoke the SDK.

First, I removed all contents of /home/.local/lib/python3.10/site-packages

AtriumDB.def (found in lib-tsc):
__________
Bootstrap: docker
From: ubuntu:latest

%post
    export DEBIAN_FRONTEND=noninteractive
    apt-get update && apt-get install -y tzdata cmake build-essential gdb libzstd-dev liblz4-dev python3.10 mingw-w64 python3-pip
    pip install numpy
    pip install atriumdb
    rm -rf /var/lib/apt/lists/*

    sed -i -e 's/\r$//' /build_release.sh
    sed -i -e 's/\r$//' /build_debug.sh

    chmod 755 /build_release.sh
    chmod 755 /build_debug.sh


%files
    build_release.sh /
    build_debug.sh /

%environment
    export TZ="America/Toronto"

%runscript
    /bin/bash
_____________

Steps, taken from /lib-tsc/

singularity build atriumdb.sif AtriumDB.def
singularity exec atriumdb.sif python3.10
>>> from atriumdb import AtriumSDK
[use as normal]

From this, I can invoke the SDK.  The key change was using pip to install AtriumDB from within the container.  I haven't tested yet, but we can probably remove several parts of the Singularity definition file as well, like including the build scripts and installing numpy separately.

I'll continue to work with this container for now, and if working from within the container isn't feasible at some point then I'll update.

**Comment by dweth** [comment]
Confirmed that these steps alone work:

Create a singularity definition file AtriumDB.def:

______________________

Bootstrap: docker
From: ubuntu:latest

%post
export DEBIAN_FRONTEND=noninteractive
apt-get update && apt-get install -y tzdata cmake build-essential gdb libzstd-dev liblz4-dev python3.10 mingw-w64 python3-pip
pip install atriumdb
#pip install any other packages you need to work with.  In my case, I needed pandas and pyarrow.
rm -rf /var/lib/apt/lists/*

%environment
export TZ="America/Toronto"

%runscript
/bin/bash

_______________________

Then build the image with 

singularity build atriumdb.sif AtriumDB.def

Then either

singularity exec atriumdb.sif python3.10

or

singularity exec atriumdb.sif bash

From here it will work within the container.  This does not require any download of the repository from GitHub.
